Default: &defaults
  database: appianAdmin.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: appianAdmin_test.sqlite3
  <<: *defaults

Staging:
  database: appianAdmin_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: appianAdmin_production.sqlite3
  poolsize: 100
  <<: *defaults
